### ISSUE TITLE
  DcParent is empty, and get its value is wrong. How to deal with it? thank you

### ISSUE THREAD

**Issue by jiangjiane** [lucksd356/DecisionTrees#1]
![screenshot from 2018-09-21 16-26-58](https://user-images.githubusercontent.com/13587284/45869805-f31b8080-bdbb-11e8-9a78-cbb0addd99e0.png)

**Comment by jiangjiane** [comment]
![screenshot from 2018-09-21 16-34-07](https://user-images.githubusercontent.com/13587284/45869893-3249d180-bdbc-11e8-816a-abc4492eaa3b.png)

**Comment by lucksd356** [comment]
Using the original code I inserted the following print statement at line 257
```python
szSplit = '%d-%s' % (iSplit, decision)
print('> insert key: %s' % szSplit)
dcParent[szSplit] = i_node
```
and another print statement at line 276
```python                
szSplit = '%d-%s' % (nSplit, szParent)
print('> look up key: %s' % szSplit)
p_node = dcParent[szSplit]
```
Here is the output from those statements:
> insert key: 1-PetalLength >= 3
> insert key: 2-PetalWidth >= 1.8
> look up key: 1-PetalLength >= 3
> look up key: 1-PetalLength >= 3
> insert key: 3-PetalLength >= 4.9
> look up key: 2-PetalWidth >= 1.8
> insert key: 3-PetalLength >= 5
> look up key: 2-PetalWidth >= 1.8
> look up key: 3-PetalLength >= 4.9
> insert key: 4-SepalLength >= 6
> look up key: 3-PetalLength >= 4.9
> insert key: 4-PetalWidth >= 1.6
> look up key: 3-PetalLength >= 5
> look up key: 3-PetalLength >= 5
> look up key: 4-SepalLength >= 6
> look up key: 4-SepalLength >= 6
> insert key: 5-SepalLength >= 7.2
> look up key: 4-PetalWidth >= 1.6
> look up key: 4-PetalWidth >= 1.6
> look up key: 5-SepalLength >= 7.2

I hope this helps.

**Comment by jiangjiane** [comment]
This is a difference about dictionary between py2 and py3. I 've solved it, thank you.
